# syntax=docker/dockerfile:1
FROM golang:1.23 AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/{{project_name}} .

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/{{project_name}} /{{project_name}}
ENTRYPOINT ["/{{project_name}}"]
